### ISSUE TITLE
Absolutely a time saver! Can you please document/expose the endpoints?

### ISSUE THREAD

**Issue by marcellodesales** [sdoxsee/env-gen#1]
That would be awesome to expose the endpoints through an API... That would be awesome... Here's what I'm thinking `Env-gen` could provide:

## .env file to config

* Convert the env file to config based on best guess
  * This is a good head-start when looking over configuration
  * I can quickly move docker-compose .env files to config properties
  * Provide hints to convert the variables with "-" (user should provide in the options calls)

## Config.yaml, Config.properties or Config.json to .env 

* This is a giver... it's already implemented in the main website...
  * Just a converter API would be awesome
* Persisting a Json file in a github repo for config server is an option for some requirements
  * https://stackoverflow.com/questions/31698783/can-i-host-json-file-in-spring-cloud-config-server/50244824#50244824

## Config.yaml, Config.properties or Config.json to Kubernetes Configmap

* That would be great to just get the object created :)

**Comment by sdoxsee** [comment]
Thanks for the ideas and feedback @marcellodesales. I know the code isn't pristine, but would you be up for submitting a PR?

**Comment by marcellodesales** [comment]
@sdoxsee If I had time I would!!!

**Comment by sdoxsee** [comment]
@marcellodesales I get it. I think your suggestions are great! I'll race you to get them done but lacking bandwidth myself at the moment 😂 Will leave this issue open in the meantime

**Comment by sdoxsee** [comment]
@marcellodesales what kind of API are you referring to again? I won't create an API that can be called by HTTP request. This is deliberately a client-side only application. If you're referring to something else, let me know know and I'll re-open. Thanks.

**Comment by marcellodesales** [comment]
@sdoxsee Exposing the same API that you have for clients would allow anyone to offer a micro-service that could translate KV pairs of env vars to K8S/Docker Env configuration... Why wouldn't you create an API to be called directly by HTTP??? That's just  a shame... I will fork your project and do it myself... 

thank you

**Comment by sdoxsee** [comment]
I don't want a server side component because I want people to more easily trust the site--knowing I won't be storing and distributing their secrets on a server somewhere.

It's also more infrastructure and I have no need for it right now.

Definitely feel free to fork if you'd like. Thanks!

**Comment by marcellodesales** [comment]
Your idea is good and can be used by others :) If you run your own engineering group, that would come handy... Not necessarily use your own infra or trust your website... I would not trust your infra myself because I can't see where you are running it either :)

Needless to say, thank you for your code and certainly will have someone to work on it at some point 👍
